[04/Aug/2017 11:22:05] ERROR [django.request:135] Internal Server Error: /admin/
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python34\lib\site-packages\django\core\handlers\base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "C:\Python34\lib\site-packages\django\core\handlers\base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python34\lib\site-packages\django\core\handlers\base.py", line 215, in _get_response
    response = response.render()
  File "C:\Python34\lib\site-packages\django\template\response.py", line 107, in render
    self.content = self.rendered_content
  File "C:\Python34\lib\site-packages\django\template\response.py", line 84, in rendered_content
    content = template.render(context, self._request)
  File "C:\Python34\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 207, in render
    return self._render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "C:\Python34\lib\site-packages\django\template\loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "C:\Python34\lib\site-packages\django\template\loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "C:\Python34\lib\site-packages\django\template\loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "C:\Python34\lib\site-packages\django\templatetags\static.py", line 105, in render
    url = self.url(context)
  File "C:\Python34\lib\site-packages\django\templatetags\static.py", line 102, in url
    return self.handle_simple(path)
  File "C:\Python34\lib\site-packages\django\templatetags\static.py", line 117, in handle_simple
    return staticfiles_storage.url(path)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\storage.py", line 162, in url
    return self._url(self.stored_name, name, force)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\storage.py", line 141, in _url
    hashed_name = hashed_name_func(*args)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\storage.py", line 432, in stored_name
    raise ValueError("Missing staticfiles manifest entry for '%s'" % clean_name)
ValueError: Missing staticfiles manifest entry for 'admin/css/base.css'
[04/Aug/2017 11:22:05] ERROR [django.server:124] "GET /admin/ HTTP/1.1" 500 27
[04/Aug/2017 11:22:07] ERROR [django.request:135] Internal Server Error: /admin/
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python34\lib\site-packages\django\core\handlers\base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "C:\Python34\lib\site-packages\django\core\handlers\base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python34\lib\site-packages\django\core\handlers\base.py", line 215, in _get_response
    response = response.render()
  File "C:\Python34\lib\site-packages\django\template\response.py", line 107, in render
    self.content = self.rendered_content
  File "C:\Python34\lib\site-packages\django\template\response.py", line 84, in rendered_content
    content = template.render(context, self._request)
  File "C:\Python34\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 207, in render
    return self._render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "C:\Python34\lib\site-packages\django\template\loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "C:\Python34\lib\site-packages\django\template\loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "C:\Python34\lib\site-packages\django\template\loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "C:\Python34\lib\site-packages\django\templatetags\static.py", line 105, in render
    url = self.url(context)
  File "C:\Python34\lib\site-packages\django\templatetags\static.py", line 102, in url
    return self.handle_simple(path)
  File "C:\Python34\lib\site-packages\django\templatetags\static.py", line 117, in handle_simple
    return staticfiles_storage.url(path)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\storage.py", line 162, in url
    return self._url(self.stored_name, name, force)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\storage.py", line 141, in _url
    hashed_name = hashed_name_func(*args)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\storage.py", line 432, in stored_name
    raise ValueError("Missing staticfiles manifest entry for '%s'" % clean_name)
ValueError: Missing staticfiles manifest entry for 'admin/css/base.css'
[04/Aug/2017 11:22:07] ERROR [django.server:124] "GET /admin/ HTTP/1.1" 500 27
[04/Aug/2017 11:22:08] ERROR [django.request:135] Internal Server Error: /admin/
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python34\lib\site-packages\django\core\handlers\base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "C:\Python34\lib\site-packages\django\core\handlers\base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python34\lib\site-packages\django\core\handlers\base.py", line 215, in _get_response
    response = response.render()
  File "C:\Python34\lib\site-packages\django\template\response.py", line 107, in render
    self.content = self.rendered_content
  File "C:\Python34\lib\site-packages\django\template\response.py", line 84, in rendered_content
    content = template.render(context, self._request)
  File "C:\Python34\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 207, in render
    return self._render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "C:\Python34\lib\site-packages\django\template\loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "C:\Python34\lib\site-packages\django\template\loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "C:\Python34\lib\site-packages\django\template\loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "C:\Python34\lib\site-packages\django\templatetags\static.py", line 105, in render
    url = self.url(context)
  File "C:\Python34\lib\site-packages\django\templatetags\static.py", line 102, in url
    return self.handle_simple(path)
  File "C:\Python34\lib\site-packages\django\templatetags\static.py", line 117, in handle_simple
    return staticfiles_storage.url(path)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\storage.py", line 162, in url
    return self._url(self.stored_name, name, force)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\storage.py", line 141, in _url
    hashed_name = hashed_name_func(*args)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\storage.py", line 432, in stored_name
    raise ValueError("Missing staticfiles manifest entry for '%s'" % clean_name)
ValueError: Missing staticfiles manifest entry for 'admin/css/base.css'
[04/Aug/2017 11:22:08] ERROR [django.server:124] "GET /admin/ HTTP/1.1" 500 27
